### ISSUE TITLE
Collect assets/images from the cultural club

### ISSUE THREAD

**Issue by Welf06** [samhitha-b/wildbeats#4]

**Comment by jeanj0n** [comment]
I would like to claim this issue and get more detail on how to proceed

**Comment by Welf06** [comment]
> I would like to claim this issue and get more detail on how to proceed

Please give the details like name, roll no. , discord id so that we know who you are and how to contact you.

**Comment by jeanj0n** [comment]
Name: Jean Joseph
Roll No. : 2021BCY0003
email: jean21bcy3@iiitkottayam.ac.in
