### ISSUE TITLE
Code the Art sub club page. 

### ISSUE THREAD

**Issue by Welf06** [samhitha-b/wildbeats#8]
Work can begin after designs are made

**Comment by niranjannagumalli** [comment]
I would like to claim this issue and get more details regarding this issue.

**Comment by achiverram28** [comment]
I would like to claim this issue because I already have some experience with good amt of js

**Comment by VictoriousKnight** [comment]
I'd like to claim this issue because I have a fair experienc in HTML. I don't know about CSS or JavaScript, but I'll take care that I'll master them in upcoming weeks.
